### ISSUE TITLE
Enhancement suggestion: tagging multiple text fields concurrently in a single request

### ISSUE THREAD

**Issue by simonatdrg** [OpenSextant/SolrTextTagger#35]
Would it be feasible to extend the API so that one could submit several separate text fields to be tagged in a single HTTP request, and do the tagging concurrently (in multiple threads). I suggest this because
a) we have a use case for this and b) it would be nice to take advantage of multicore/multiprocessor environments where possible.

At the moment I'm achieving concurrency in my application (written in Python) , but that involves creating threads, each of which then has to issue its own HTTP request. 

Thoughts ?

**Comment by dsmiley** [comment]
It's feasible in the sense if you want to do it, you could add it.  You'd need to figure out how the client will send multiple blocks of text and correspondingly how the multiple responses go in the output.  I *think* multiple blocks of text could be sent via MIME multi-part.  Ultimately, I don't think it would be very _clean_, API / design wise... it'll seem like a bolted on feature.  

But If you think about it... there may be no problem to be solved here -- why not use a feature of HTTP: "HTTP Pipelining"?  http://en.wikipedia.org/wiki/HTTP_pipelining  Does your Python library support "HTTP Pipelining"?  It allows for one TCP/IP connection with a stream of HTTP requests going in and responses coming out.  Browsers do it but I've found most libraries don't, unfortunately.  All HTTP 1.1 servers support it but it's up to the server to decide how to dispatch the requests -- in serial or concurrently; who knows.  More likely in serial but that's okay because you can still use multiple requests on the client side and know that there isn't needless TCP/IP connections being created per message.

**Comment by simonatdrg** [comment]
Thanks.
I  sort of agree about the bolted-on ness...  . Wasn't aware of HTTP pipelining - will take a look to see if that could be a solution. Alternatively, It does look as though the Python Requests and urllib3 modules support HTTP connection caching which would go some way towards reducing TCP overhead.

Thinking about the problem some more -  it may be that the simplest thing to do is for the client to concatenate the fields (we often have lots of small fields in a single document,  each of which needs to be tagged separately, which is what triggered my post) separating them by an artificial token which can't occur in our entity dictionaries,  and send  that on to the tagger. The position information in the response can then  be used to assign each tag back to its correct field.

**Comment by dsmiley** [comment]
That makes sense... kind of a hack perhaps but very simple, efficient, and effective :-)
