### ISSUE TITLE
Supplementing filter query with request filter query. 

### ISSUE THREAD

**Issue by jdeolive** [OpenSextant/SolrTextTagger#37]
Apologies if this the wrong forum for such a question, but I didn't a forum or mailing list for the project. We're using the text tagger along with the gazetteer with a configuration that sets some defaults for filter query. The configuration per se was taken from [here|https://github.com/OpenSextant/Xponents/blob/master/solr/gazetteer/conf/solrconfig.xml#L810].

However, we need to be able to specify an additional constraint "on the fly". For example to constrain tagging to a specific country code. The behaviour as I understand it is that if there is a configured filter query in solrconfig.xml it trumps any filter query supplied by the request. 

I couldn't find a way (that wasn't a total hack) to join the two filter queries. What I've done for now is patch TaggerRequestHandler and made setTopInitArgsAsInvariants() protected so I can subclass it and do the "ANDing" there. 

I guess my questions are (a) is there is a way to do this already that I am missing, and (b) if not, is something like what I've done acceptable?

**Comment by dsmiley** [comment]
Hi Justin.  There is no forum or mailing list to my knowledge.

The earlier versions of the tagger request handler configured stuff at the top-level instead of following standard default/appends/invariants conventions.  That still works but is deprecated; you should put all parameters in "defaults" or "invariants" as applicable.  The solrconfig.xml you reference uses a mixed style; it really should be updated to minimize confusion.  I *think* that if you put 'fq' in the defaults section, that the request will override it.  If it doesn't work then it's a bug!  I would like to keep setTopInitArgsAsInvariants private as it's likely to go away once we cut compatibility with the old style config, but it's not important.

But nonetheless the tagger only supports one 'fq' query, unlike a standard Solr search.  It should be easy to add; "searcher.getDocSet(filterQuery)" takes a list of queries as well.  Pull requests are welcome :-)

**Comment by jdeolive** [comment]
Thanks David! Using fq in "appends" along with handling multiple fq's in computeDocCorpus gives me what i need. I'll work on the pull request.

**Comment by mubaldino** [comment]
Hi Justin, 

No mailing list currently.

The Xponents/Extraction/  geo pkg has a SolrGazetteer and a GazetteerMatcher that make use of the gazetteer core directly.   SolrGaz facilitates the most common search routines, while GazMatcher is the SolrTextTagger implementation where the "/tag"  request processor comes into play.   So, GazMatcher is the class I'd target for adding this live feature -- adapting the solr params to /tag, such as extending the "fq" or other params.

I'm working on Xponents v2.7d SNAPSHOT -- in master;   Currently running through testing that... Once 2.7.1 is finally released (after going through a,b,c,d fix up releases), I'll start managing changes off in branches.    Overdue for a documentation release, too.

thanks for the feedback.

Marc
