### ISSUE TITLE
API change in Solr 6.3 [SOLR-9592]

### ISSUE THREAD

**Issue by westei** [OpenSextant/SolrTextTagger#60]
The current version of SolrTextTagger does not work with Solr 6.3 because `SolrIndexSearcher#getLeafReader` was renamed to `SolrIndexSearcher#getSlowAtomicReader` ([SOLR-9592](https://issues.apache.org/jira/browse/SOLR-9592)).

Changing the code would mean that the most current version of SolrTextTagger would no longer work with Solr/Lucene versions < 6.3. So most likely this would require a new release to be used with Solr 6.3+

In addition the javadoc indicates that one should use `IndexSearcher.leafContexts` instead. However this field is protected so I am not sure how to use it.

**Comment by dsmiley** [comment]
Hi Rupert.
Maybe just do this via reflection... since it's just this method and it isn't used in a hot loop?

That javadoc reference to `IndexSearcher.leafContexts` perhaps assumed from the context of SolrIndexSearcher itself since it's protected.  If you wanted the leaves, you could grab the IndexReader and cast to CompositeReader then go from there.  Any way, despite the name "Slow" it's appropriate for some uses.  "Slow" in the name is supposed to scare people off from inadvertent usage.  We use it here in an appropriate way.  The recommended usage of the SolrTextTagger is to use an optimized index.  In that case, you will get a bonafide LeafReader that is not SlowCompositeReaderWrapper.  And if you couldn't realistically optimize to one segment, it would be difficult to write a version of the text tagger that operated per-segment; it might actually perform slower than using SlowCompositeReaderWrapper.  By "Difficult" I should clarify it's quite do-able but would add complexity and IMO it's not worth it.

**Comment by westei** [comment]
Hi,

That's exactly the information I was looking for. I was assuming something like that as the method was just renamed and their where no actual changes in the implementation.

I will provide a patch for the API change that works with both Solr `< 6.2.1` and and `> 6.3.0`.

best
Rupert

**Comment by dsmiley** [comment]
Thanks for helping.
