### ISSUE TITLE
htmlOffsetAdjust and matchText enabled gets StringIndexOutOfBoundsException 

### ISSUE THREAD

**Issue by jigarparekh80** [OpenSextant/SolrTextTagger#84]
Hi,

I am getting string index out of bound error if i have htmlOffsetAdjust and matchText enabled, below stack trace 

```
null:java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at org.opensextant.solrtexttagger.TaggerRequestHandler$1.tagCallback(TaggerRequestHandler.java:193)
	at org.opensextant.solrtexttagger.Tagger.advanceTagsAndProcessClusterIfDone(Tagger.java:210)
	at org.opensextant.solrtexttagger.Tagger.process(Tagger.java:152)
```

Testcase 

```
buildNames("start end");
assertXmlTag("start <td/> end", true);
```

i have tried to correct HtmlOffsetCorrector but could not get through, finally i had to change TaggerRequestHandler.handleRequestBody Line 186 

from 
   endOffset = offsetPair[1];
to 
  endOffset = offsetPair[1]<0?inputString.length():offsetPair[1];

can there be better fix for this?

**Comment by dsmiley** [comment]
Thanks for reporting... I didn't get a chance to look today but will hopefully look closer tomorrow (Friday).

**Comment by jigarparekh80** [comment]
Thanks, i guess ignoring wrong offset correction might also one solution 

```
              if(offsetPair[0]>=0 && offsetPair[1]>=0 ) {
            	  startOffset = offsetPair[0];
              	  endOffset = offsetPair[1];
              }
```

**Comment by dsmiley** [comment]
I'd rather not put band-aids on the consumption end; I'd rather have reasonable offsets at the source end.  Thus -- fix the bug.  Thanks for sample data... I ran it through a debugger and it appears we need to call startTag.isSyntacticalEmptyElementTag().  It's not completely clear if testing this actually requires more than one tag; if not you can leave `assertXmlTag` alone.  Can you work on a fix with test?

**Comment by jigarparekh80** [comment]
Thanks applied fix. change to asertXmlTag is not required, i was trying to add testcase according to exact scenario i had encountered but this fix does not need it. 
updated pull request.

**Comment by jigarparekh80** [comment]
is there any reason, html offset corrector have not been migrated to apache solr? I was planning to move everything solr 7.4 so trying to find if it has any missing feature.

**Comment by dsmiley** [comment]
I wasn't quite comfortable with adding yet another dependency for an optional feature of a fringe feature of everyone using Solr.  And I have doubts about the overall approach... it works, isn't bad but it'd be really nice if (somehow) the HtmlStripCharFilterFactory (or derivative) analysis component handled this sort of thing instead of the tagger itself needing to have such a feature, which feels a bit bolted on.  I don't have the bandwidth to tackle redoing it though.  
https://github.com/OpenSextant/SolrTextTagger/issues/28#issuecomment-385785415

**Comment by dsmiley** [comment]
BTW a TODO in this project is to extend the hander shipping in Solr 7.4 to provide the htmlOffsetAdjust option.  I had this in mind when I ported it to Solr so that this feature could be added separately.  Perhaps that would be a separate branch which only provides that feature, tests, that, and does nothing else.
